unit TestILoadObject;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,
  AWS.S3,
  System.Classes, System.SysUtils,
//  ILoadValue,
//  ILoadObject,
  interfaces, model,
  System.Diagnostics,
  Vcl.Forms,
  AWS.S3.ClientIntf, AWS.S3.Client;

type
  // Test methods for class TLoad

  TestTLoad = class(TTestCase)
  strict private
    FLoad: ILoad;
    FSettings: ISettings;
  public
    procedure SetUp; override;
    procedure TearDown; override;
    function OnProgress(aLoad: ILoad; aType: TEventType): Boolean;
    procedure StartAndWait;
  published
    procedure TestStart;
    procedure TestMultiStart;
    procedure TestAndBreak;
  end;

implementation

function TestTLoad.OnProgress(aLoad: ILoad; aType: TEventType): Boolean;
begin
  case aType of
    tetOnStart: Status('Пуск');
//    tetOnprogress: Status(IntToStr(aLoad.Progress) + '%');
    tetOnFinish: Status('Завершено');
  end;
  Result:=True;
end;

procedure TestTLoad.SetUp;
var FS: TFormatSettings;
begin
  FS:=TFormatSettings.Create('en-US');
  FS.ShortDateFormat := 'dd mmm yyyy';
  FS.LongTimeFormat := 'hh:nn:ss';
//  TryStrToDateTime('16 Jul 2026 15:05:11')


  FSettings:=SettingsFab.Settings;
  FSettings.LoadList.Add(SettingsFab.NewLoadSetup);
  with FSettings.LoadList.Items[0] do
  begin
//    LoadData[tldName]:='c:/test/1.txt';
    LoadData[tldEndpoint]:='https://s3.bazissoft.ru';
    LoadData[tldBucket]:='recruiting';
    LoadData[tldAccessKey]:='candidate';
    LoadData[tldSecretkey]:='OS0jIQ{SS6';
    LoadData[tldRegion]:='ru-central';
  end;
  FLoad:=LoadFab.NewLoad(FSettings, 0);
  FLoad.SetOnEvent(OnProgress);
end;

procedure TestTLoad.StartAndWait;
begin
  FLoad.Start;
  //ждём
  while not (FLoad.Status in [tlsDone, tlsStop]) do
  begin
    Application.ProcessMessages;
    Sleep(100);
  end;
end;

procedure TestTLoad.TearDown;
begin
  FLoad := nil;
end;

procedure TestTLoad.TestAndBreak;
begin
  FSettings.LoadList.Items[0].LoadData[tldName]:='c:/test/s3test';
  FLoad.Start;
  //ждём
  for var I:=0 to 10 do
  begin
    if (FLoad.Status in [tlsDone, tlsStop]) then
      Break;
    Application.ProcessMessages;
    Sleep(100);
  end;
  FLoad.Stop;
  while not (FLoad.Status in [tlsDone, tlsStop]) do
  begin
    Application.ProcessMessages;
    Sleep(100);
  end;
end;

procedure TestTLoad.TestMultiStart;
begin
  FSettings.LoadList.Items[0].LoadData[tldName]:='c:/test/s3test';
  StartAndWait;
end;

procedure TestTLoad.TestStart;
begin
  FSettings.LoadList.Items[0].LoadData[tldName]:='c:/test/1.txt';
  StartAndWait;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTLoad.Suite);
end.

